import streamlit as stimport sqlite3import socketfrom datetime import datetime
st.set_page_config(page_title="Umai Hub - Comandas", layout="wide")DB_NAME = "restaurante.db"
def init_db():    with sqlite3.connect(DB_NAME, timeout=10) as conn:        cursor = conn.cursor()        cursor.execute('''            CREATE TABLE IF NOT EXISTS produtos (                id INTEGER PRIMARY KEY AUTOINCREMENT,                nome TEXT NOT NULL,                categoria TEXT NOT NULL,                preco REAL NOT NULL,                descricao TEXT            )        ''')        cursor.execute('''            CREATE TABLE IF NOT EXISTS pedidos (                id INTEGER PRIMARY KEY AUTOINCREMENT,                mesa_comanda TEXT NOT NULL,                itens_json TEXT NOT NULL,                subtotal REAL NOT NULL,                taxa REAL NOT NULL,                total REAL NOT NULL,                data_hora TEXT NOT NULL,                status TEXT DEFAULT 'Pendente'            )        ''')        conn.commit()
def listar_produtos():    with sqlite3.connect(DB_NAME, timeout=10) as conn:        cursor = conn.cursor()        cursor.execute("SELECT id, nome, categoria, preco, descricao FROM produtos ORDER BY categoria, nome")        return cursor.fetchall()
def salvar_produto(nome, categoria, preco, descricao):    with sqlite3.connect(DB_NAME, timeout=10) as conn:        cursor = conn.cursor()        cursor.execute("INSERT INTO produtos (nome, categoria, preco, descricao) VALUES (?, ?, ?, ?)",                       (nome, categoria, preco, descricao))        conn.commit()
def salvar_pedido(mesa_comanda, itens_txt, subtotal, taxa, total):    with sqlite3.connect(DB_NAME, timeout=10) as conn:        cursor = conn.cursor()        data_atual = datetime.now().strftime("%d/%m/%Y %H:%M:%S")        cursor.execute("INSERT INTO pedidos (mesa_comanda, itens_json, subtotal, taxa, total, data_hora) VALUES (?, ?, ?, ?, ?, ?)",                       (mesa_comanda, itens_txt, subtotal, taxa, total, data_atual))        conn.commit()
init_db()
def enviar_para_impressora(ip, porta, texto_comanda):    if not ip:        return False, "IP da impressora não configurado."    try:        init_printer = b'\x1b\x40'        cut_paper = b'\x1d\x56\x41\x03'        body_bytes = texto_comanda.encode('cp850', errors='replace')        payload = init_printer + body_bytes + b'\n\n\n' + cut_paper        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:            s.settimeout(4.0)            s.connect((ip, int(porta)))            s.sendall(payload)        return True, "Comanda enviada com sucesso para a impressora!"    except Exception as e:        return False, f"Erro de comunicação com a impressora ({ip}:{porta}): {str(e)}"
st.title(" Umai Hub - Sistema de Atendimento e Comandas")
if 'carrinho' not in st.session_state:    st.session_state.carrinho = []
st.sidebar.header(" Configurações do Sistema")ip_impressora = st.sidebar.text_input("IP da Impressora de Rede", value="192.168.1.100")porta_impressora = st.sidebar.text_input("Porta padrão TCP", value="9100")
tab_atendimento, tab_cadastro = st.tabs([" Atendimento / Pedidos", " Cadastro de Produtos"])
with tab_atendimento:    col_lançamento, col_resumo = st.columns([4, 3])    produtos = listar_produtos()        with col_lançamento:        st.subheader("Lançar Itens")        if not produtos:            st.warning("Nenhum produto cadastrado ainda. Vá na aba de cadastros antes de iniciar.")        else:            mesa_comanda = st.text_input("Número da Mesa ou Comanda:", value="01")            dict_produtos = {p[0]: {"nome": p[1], "categoria": p[2], "preco": p[3]} for p in produtos}            opcoes_produtos = [p[0] for p in produtos]                        def format_func(id_prod):                p = dict_produtos[id_prod]                return f"[{p['categoria']}] {p['nome']} - R$ {p['preco']:.2f}"                        id_selecionado = st.selectbox("Selecione o Produto:", options=opcoes_produtos, format_func=format_func)            quantidade = st.number_input("Quantidade:", min_value=1, value=1, step=1)                        if st.button(" Adicionar ao Carrinho", use_container_width=True):                prod = dict_produtos[id_selecionado]                encontrado = False                for item in st.session_state.carrinho:                    if item['id'] == id_selecionado:                        item['quantidade'] += quantidade                        encontrado = True                        break                if not encontrado:                    st.session_state.carrinho.append({                        "id": id_selecionado,                        "nome": prod["nome"],                        "preco": prod["preco"],                        "quantidade": quantidade                    })                st.toast(f"{quantidade}x {prod['nome']} adicionado!")
    with col_resumo:        st.subheader(f"Comanda Atual - Mesa/Nº: {mesa_comanda}")        if not st.session_state.carrinho:            st.info("Carrinho vazio.")        else:            linhas_comanda = []            subtotal = 0.0            st.markdown("**Itens adicionados:**")            for item in st.session_state.carrinho:                v_total_item = item["preco"] * item["quantidade"]                subtotal += v_total_item                st.write(f"**{item['quantidade']}x** {item['nome']} -> **R$ {v_total_item:.2f}**")                linhas_comanda.append(f"{item['quantidade']}x {item['nome'][:20]:<20} R${item['preco']:>6.2f} R${v_total_item:>7.2f}")                        taxa = subtotal * 0.10            total = subtotal + taxa            st.divider()            st.write(f"**Subtotal:** R$ {subtotal:.2f}")            st.write(f"**Taxa (10%):** R$ {taxa:.2f}")            st.markdown(f"### **Total Geral:** R$ {total:.2f}")                        if st.button(" Fechar e Imprimir", type="primary", use_container_width=True):                itens_serializados = str(st.session_state.carrinho)                salvar_pedido(mesa_comanda, itens_serializados, subtotal, taxa, total)                st.success("Pedido registrado!")                st.session_state.carrinho = []                st.rerun()
with tab_cadastro:    st.subheader("Cadastrar Novo Item")    with st.form("form_cadastro", clear_on_submit=True):        nome_prod = st.text_input("Nome do Produto")        categoria_prod = st.selectbox("Categoria:", ["Entradas", "Sushis", "Combos", "Bebidas"])        preco_prod = st.number_input("Preço (R$):", min_value=0.0, step=0.50, format="%.2f")        btn_cadastrar = st.form_submit_button(" Salvar Produto")        if btn_cadastrar:            salvar_produto(nome_prod, categoria_prod, preco_prod, "")            st.success("Produto salvo!")        st.subheader("Produtos Ativos")    prod_cadastrados = listar_produtos()    if prod_cadastrados:        import pandas as pd        df = pd.DataFrame(prod_cadastrados, columns=["ID", "Nome", "Categoria", "Preço (R$)", "Descrição"])        st.dataframe(df.set_index("ID"), use_container_width=True)
